version: "3"

services:
  reverseproxy:
    image: reverseproxy
    build:
      context: ./config/proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - iam
      - shortener

  iam-db:
    image: postgres:latest
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  shortener-db:
    image: postgres:latest
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  iam:
    image: iam
    command: bash -c "npm run migrate && npm run start"
    build:
      context: ./apps/iam
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=prod
      - SERVER_PORT=80
      - SERVER_NAME=iam-node
      - TOKEN_SECRET=secret
      - DB_PORT=5432
      - DB_HOST=iam-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - AMQP_URL=amqp://rabbitmq
      - SERVER_URL=http://localhost:80/
    depends_on:
      iam-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  shortener:
    image: shortener
    command: bash -c "npm run migrate && npm run start"
    build:
      context: ./apps/shortener
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=prod
      - SERVER_PORT=80
      - SERVER_NAME=shortener-node
      - TOKEN_SECRET=secret
      - DB_PORT=5432
      - DB_HOST=shortener-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - AMQP_URL=amqp://rabbitmq
      - SERVER_URL=http://localhost:80/
    depends_on:
      shortener-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
